/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Rahul Gill",
  "tagline": "I am a Student and Software Engineer passionate about solving Meaningful Problems.",
  "url": "https://rahul-gill.github.io",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "favicon": "img/logo.png",
  "organizationName": "rahul-gill",
  "projectName": "rahul-gill.github.io",
  "trailingSlash": false,
  "deploymentBranch": "gh-pages",
  "plugins": [
    "posthog-docusaurus"
  ],
  "themeConfig": {
    "prism": {
      "additionalLanguages": [
        "kotlin",
        "sql"
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "Rahul Gill",
      "logo": {
        "alt": "Rahul GIll",
        "src": "img/logo.png",
        "href": "https://rahul-gill.github.io",
        "target": "_self"
      },
      "items": [
        {
          "to": "blog/",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "docs/",
          "activeBasePath": "docs",
          "label": "Docs",
          "position": "left"
        },
        {
          "to": "projects/",
          "label": "Projects",
          "position": "right"
        },
        {
          "to": "about/",
          "label": "About",
          "position": "right"
        },
        {
          "href": "https://drive.google.com/file/d/1ZsqIyDdkrzXBqItw9YmDtEKZ4pY7EKSl/view?usp=sharing",
          "label": "Resume",
          "position": "right"
        }
      ]
    },
    "footer": {
      "links": [
        {
          "title": "Connect",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/rahul-gill-466a1620a/"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/rahul-gill"
            },
            {
              "label": "Email",
              "href": "mailto:rgill1@protonmail.com"
            }
          ]
        },
        {
          "title": "Discover",
          "items": [
            {
              "label": "Blog",
              "to": "blog"
            },
            {
              "label": "Documentation",
              "to": "docs"
            },
            {
              "label": "Projects",
              "to": "projects"
            },
            {
              "label": "About",
              "to": "about"
            },
            {
              "label": "Resume",
              "href": "https://drive.google.com/file/d/1ZsqIyDdkrzXBqItw9YmDtEKZ4pY7EKSl/view?usp=sharing"
            }
          ]
        },
        {
          "title": "Credits",
          "items": [
            {
              "label": "Evan Tay",
              "href": "https://evantay.com/"
            },
            {
              "label": "Docusaurus",
              "href": "https://docusaurus.io/"
            }
          ]
        }
      ],
      "copyright": "Last updated on Sat Jun 11 2022 ",
      "style": "light"
    },
    "posthog": {
      "apiKey": "DEV",
      "enableInDevelopment": false
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/home/ashen-one/Desktop/kaya-folio/sidebars.js",
          "disableVersioning": false,
          "editCurrentVersion": false,
          "remarkPlugins": [
            null,
            [
              null,
              {
                "mermaid": {
                  "theme": "dark"
                }
              }
            ]
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": {
          "blogSidebarTitle": "Recent posts",
          "blogSidebarCount": "ALL",
          "showReadingTime": true,
          "editUrl": "https://github.com/rahul-gill/rahul-gill.github.io"
        },
        "theme": {
          "customCss": "/home/ashen-one/Desktop/kaya-folio/src/css/custom.css"
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X",
      "crossorigin": "anonymous"
    }
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
